[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "panel attack quick evoke guilt faith express solid reward rocket betray address wave rhythm alter woman mobile shoe play valid film glance food marriage"